### ISSUE TITLE
How to fit a VMA(1) model?

### ISSUE THREAD

**Issue by travis-leith** [ineswilms/bigtime#3]
I have some data for which I have good reason to believe would suit a VMA(1) model.
I want to compare this package to MTS. But bigtime does not let me specify maxp to be 0.
Is there a way around this? Maybe this can be considered a feature request.

**Comment by enweg** [comment]
This does indeed not work in the current master, nor in the development branch. A workaround that currently works in the development branch is to set `VARMAlPhiseq` to a very large number.

Example:
`mod <- sparseVARMA(scale(Y), VARMAlPhiseq = 1000, VARMAselection = "cv") # Works on README data`

Which then sets all  Phi coefficients to zero.
