### ISSUE TITLE
Error when fitting a sparseVARMA with h != 1 and selection procedure != cv

### ISSUE THREAD

**Issue by jonlachmann** [ineswilms/bigtime#4]
After reading your interesting paper on sparse cointegration models I found this package implementing sparse varma models.

I am looking at applying the package for forecasting, why I want to be able to select a horizon larger than 1. I actually have two issues, but I will post them separately to avoid confusion.

The first problem that I experience is that when I fit a sparseVARMA model and select a horizon that is not equal to 1 and have not selected to use cross validation I get an error when the function tries to calculate residuals. Here is an example of how to reproduce the problem. Please let me know if I can be of any more assistance in describing the problem.

```
# Install the package from github
devtools::install_github("ineswilms/bigtime")
library(bigtime)

# Error when fitting a model using h != 1 and not specifying VARMAselection
testdata <- matrix(rnorm(300, 1:300), 100)
varmamod <- sparseVARMA(Y = scale(testdata), h=2)
# Error in res[, , i] <- residuals.bigtime.VARX(mod_tmp, ...): number of items to replace is not a multiple of replacement length
```

**Comment by enweg** [comment]
Many thanks for bringing this to our attention and providing a simple example. The issue should now be fixed and you should now be able to estimate VARMA models with forecasting horizons larger than one. The example has also been included in the testing procedure, so future updates should not break it.
