### ISSUE TITLE
When creating a h != 1 forecast using "directforecast" for a sparseVARMA model, only the last point is returned

### ISSUE THREAD

**Issue by jonlachmann** [ineswilms/bigtime#5]
This is the second issue that I am having. I have created a model using sparseVARMA with h=10 and cross validation. I then go on to create a forecast, but I only receive the final point of the forecast. After debugging for a bit it seems that the previous forecast points are not created.

I have created a minimum example to demonstrate the issue, please let me know if I can be of any more assitance in describing the issue I am having or debugging the code etc.

```
# Install the package from github
devtools::install_github("ineswilms/bigtime")
library(bigtime)

# Create some data and fit the model with the intention of making a 10 step forecast
set.seed(123)
testdata <- matrix(rnorm(300, 1:300), 100)
varmamod <- sparseVARMA(Y = scale(testdata), h=10, VARMAselection = "cv")

# The forecast appears to be only for t=T+10, and not for t=(T+1, T+2, ..., T+10)
directforecast(varmamod, h=10) * sqrt(diag(var(testdata))) + colMeans(testdata)
# [1] 109.4170 209.0464 309.5970
# It is expected to be 10 rows, from ~(101, 201, 301) to ~(111, 211, 311)
```

**Comment by ineswilms** [comment]
Thanks for your interest in bigtime. The direct forecast function deliberately delivers only the forecast at horizon h=10: with the direct forecast approach a separate model needs to be estimated for each forecast horizon. Hence if you would need to have the forecasts at horizons h=1...9 as well, you need to first estimate the sparseVARMA model (for that particular h), then apply the directforecast function.
